### ISSUE TITLE
Sfc5xxxUnit documentation indicates 1013 hPa as reference pressure -- really!?

### ISSUE THREAD

**Issue by brennmat** [Sensirion/python-shdlc-sfc5xxx#1]
The documentation of Sfc5xxxUnit indicates 1013 hPa as reference pressure for the NORM_LITER and STANDARD_LITER units, whereas the commonly used value would rather be 1.0 atm or 1013.25 hPa.

Is the 1013 value in the documentation just truncated from 1013.25? Or, in other words: does the code use 1013.25 hPa or 1013.00 hPa?

I'd suggest to change the 1013 value in the documentation to 1013.25 or 1013.00 (or whatever the value is) to reflect the pressure reference used in the code.

**Comment by ubruhin** [comment]
Hi,

Basically the documentation in this driver just reflects the values from the SFC5xxx datasheets where 1013 hPa is specified. And yes you're right, it is actually 1013.25 hPa implemented but the decimals are truncated in the datasheet and thus also in this documentation.

Thanks for the hint!
