### ISSUE TITLE
Documentation: difference between Sfc5xxxShdlcDevice.get_calibration_initial_conditions() and Sfc5xxxShdlcDevice. get_calibration_recalibration_conditions() is unclear

### ISSUE THREAD

**Issue by brennmat** [Sensirion/python-shdlc-sfc5xxx#3]
The documentation says the follwoing:

Sfc5xxxShdlcDevice. get_calibration_recalibration_conditions(index)
Get the recalibration conditions of a specific calibration index.
    
Sfc5xxxShdlcDevice.get_calibration_initial_conditions(index)
Get the initial calibration conditions of a specific calibration index.

However, the difference between "initial calibration" and "recalibration" is unclear to me. As far as I can tell, the SFC5xxx MFC units have a number of calibration blocks for different gas types, and they are just that: calibrations. What is an _initial_ calibration, and what it is a _re_-calibration? Why/how do these need to be treated differently?

Edit (to provide some background to my question): in the example code given at https://sensirion.github.io/python-shdlc-sfc5xxx/master/quickstart.html , how would you expand the loop showing the calibration information to also show if the the calibrations are "real gas" or "gas conversion" calibrations? Which of the two commands (initial_calibration vs recalibration) would one use?

**Comment by ubruhin** [comment]
The initial calibrations are the calibrations done during production of the MFC at Sensirion. However, each of the calibrations can be re-calibrated for example to match with a particular reference device, or to map it to a slightly different gas. This can be done either by Sensirion or by a Sensirion representative. The information about such a recalibration is then stored within the MFC, next to the initial calibration data. However, MFCs usually don't contain a recalibration if you never explicitly let your MFCs recalibrate.

If there's no recalibration, all the recalibration condition parameters are zero (e.g. "company" is an empty string). I hope this answers your questions.

**Comment by brennmat** [comment]
Thanks for this explanation, makes sense now. It would be nice to add this information to the documentation.
