### ISSUE TITLE
Accessing an sfc5xxx device from different threads

### ISSUE THREAD

**Issue by brennmat** [Sensirion/python-shdlc-sfc5xxx#4]
I couldn't find any information in the documentation if the code talking to the sfc5xxx device is thread safe or not.
Also, if it is not thread safe, how would one lock the sfc5xxx for exclusive access by only one single thread at a time?

Here's a bit of background information about the application that lead to this question:
- I am writing a GUI application that allows controlling the setpoint of an SFC5xxx MFC.
- The application also reads the flow rate from the MFC at regular intervals using a separate thread.

If the software attempts to change the setpoint at the same time as the separate thread is reading the flow rate from the MFC, the communication may become scrambled if the sfc5xxx driver is not thread safe.

**Comment by ubruhin** [comment]
The underlying [`ShdlcPort`](https://sensirion.github.io/python-shdlc-driver/api.html#shdlcport) is implemented thread safe and the higher level classes usually do not have any state and are thus automatically thread safe as well.

If it is needed to send several commands to the device without allowing another thread to interrupt, the underlying lock can be used like this:

```python
with device.connection.port.lock:
    # do something with device...
```

I created an internal ticket to document the thread safety in the driver's public documentation, thus closing this issue for now.
